export { default as Page3Card } from './page3'
export { default as Page4Card } from './page4'
export { default as Page5Card } from './page5'
export { default as Page6Card } from './page6'
export { default as Page7Card } from './page7'
